### ISSUE TITLE
Please fix IP_Block_log not send database.

### ISSUE THREAD

**Issue by vanthoi** [VictorRobellini/pfSense-Dashboard#20]
Hello.

My system information is as follows.

Pfsense: 2.4.5-RELEASE-p1
pfBlockerNG-devel | net | 2.2.5_37
Telegraf | net-mgmt | 0.9_4
Python 3.7

I recently updated the packages to new versions like pfBlockerNG-devel, Telegraf.
I have a problem with pfBlockerNG's IP blocking log no longer working.
Before everything worked perfectly.

And here is a new line of information from: /var/log/pfblockerng/ip_block.log

`Oct 29 01: 09: 49,1770010032, pppoe0, WAN, block, 4.17, UDP, 104.168.48.101,192.168.0.210,54135,5060, in, US, pfB_BlockListDE_v4, Unknown, Unknown, e1.tecnecontabil.com. br, server sip, null, -`

**Comment by a3ilson** [comment]
@vanthoi - I do not have this project running/configured yet but looking to leverage some of the work (e.g. metrics and pfBlocker-NG data to an Elastic Stack project - [pfelk](https://pfelk.3ilson.dev))

Looking at the provide log and the repo's [configuration file](https://github.com/VictorRobellini/pfSense-Dashboard/blob/master/config/additional_config.conf), it appears that the specified GROK pattern will not parse that message based on a number of syntax and formatting issues.

I'd be happy to help but curious if this particular issue impacts everyone who uses this project due to updates within the respective applications.  Additionally and once I get a variant of this running, I'll likely submit a pull request, to align the patterns with [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-field-reference.html)

**Comment by vanthoi** [comment]
@a3ilson 
Yes. I understand where the error comes from, but I don't understand the configuration file formats to edit it. You can provide a new repo snippet based on this configuration file: https://github.com/VictorRobellini/pfSense-Dashboard/blob/master/config/additional_config.conf

I will check it for you. Basically my pfSense runs new developer packages. So in the future I retire it will be useful for anyone to upgrade later.

**Comment by a3ilson** [comment]
Alright... I'll follow-up shortly with an updated conf file to try/test.

**Comment by vanthoi** [comment]
> Alright... I'll follow-up shortly with an updated conf file to try/test.

Thank you very much. Immediately after receiving support information from you. I have made a new version update for pfBlockerNG and telegraf. Then I restarted pfSense and it worked. I don't know what error the previous version had, but it hasn't been working since I sent this error message.

**Comment by a3ilson** [comment]
Great!  

Glad you got it working...I plan on leveraging the pfBlockerNG for a project I'm working on at [pfelk](https://pfelk.3ilson.dev)
