### ISSUE TITLE
OpenVPN Interfaces

### ISSUE THREAD

**Issue by StevenChorkley** [VictorRobellini/pfSense-Dashboard#35]
Hey mate, 

I'm wondering if it's possible to pull ovpn interface's with telegraf_pfinterface.php? 

Do you know if it's possible? 

Thanks in advance!

**Comment by bigjohns97** [comment]
Mine does this by default, no changes needed.

**Comment by VictorRobellini** [comment]
@bigjohns97 is correct.

**Comment by StevenChorkley** [comment]
Mine doesn't? Doesn't pull anything for ovpn interfaces.
Running 2.4.5

**Comment by StevenChorkley** [comment]
![Only interfaces are pppoe0, vmx1.40, vmx1.4093](https://user-images.githubusercontent.com/10834935/112954721-93de1a00-9136-11eb-95b2-09b4a4c81267.png)

**Comment by bigjohns97** [comment]
I am not sure what this screenshot is supposed to show us.

**Comment by bigjohns97** [comment]
Show your vpn interfaces from the pfsense side.

**Comment by StevenChorkley** [comment]
Yeah, no worries. See attached.

**Comment by StevenChorkley** [comment]
![Screenshot_20210330-145033_Firefox~2](https://user-images.githubusercontent.com/10834935/113000453-c2c0b400-9167-11eb-85fd-5012f5ee12ca.png)
![Screenshot_20210330-145135_Firefox~2](https://user-images.githubusercontent.com/10834935/113000459-c3594a80-9167-11eb-836b-ee1e0de9584d.png)
![Screenshot_20210330-145043_Firefox~2](https://user-images.githubusercontent.com/10834935/113000463-c3f1e100-9167-11eb-9d45-196a60353388.png)

**Comment by VictorRobellini** [comment]
Do those interfaces show up under pfsense Status->Interfaces?

**Comment by bigjohns97** [comment]
I'm running two servers and they both show up fine. I am not sure why his aren't showing up.

**Comment by StevenChorkley** [comment]
>Do those interfaces show up under pfsense Status->Interfaces?

No, why would they? They're OpenVPN s2s tunnels using OSPF, I've never configured them as pfsense interfaces

**Comment by VictorRobellini** [comment]
My openvpn interfaces show up in pfSense as well as my Dashboard but I'm not running frr/ospf.  In your initial request, you asked if it's possible to pull ovpn interface's with telegraf_pfinterface.php, which is what lead to the confusion. My guess is that the FRR daemon has the data you want, I'm not sure since I've never messed with it.  I don't have it set up so I can't do much here. The code that populates the [interface measurements](https://github.com/VictorRobellini/pfSense-Dashboard/blob/158a63b51e164bf47ce90b2ddef89d36e6233bdd/plugins/telegraf_pfinterface.php#L5) uses [pfsense PHP](https://github.com/pfsense/pfsense/blob/master/src/etc/inc/interfaces.inc) calls to pull data.  If you find a solution, I'll be more than happy to add it to the dashboard as long as it doesn't impact anything else.  Sorry I can't be of more help.

**Comment by StevenChorkley** [comment]
I appreciate it, thank you. Spent some time on it yesterday and managed to
pull the stats from openvpn directly.

**Comment by VictorRobellini** [comment]
This piqued my interest so I started reading.  Since I just have a client setup that's all I can toy with.  The default Ovpn config uses a local socket for the mgmt interface for the client and I would suspect it does the same for servers.

I would imagine that one of the most important parts of monitoring ovpn would be to check the state.  This is a rough way of doing it, but I may clean it up or look for a better way to get the data.

`echo state | nc -U /var/etc/openvpn/client1/sock -N | awk -F',' 'NR==2 {printf "Established=%s,Status=%s,dontknow=%s,Assigned_IP=%s,Remote_Server_IP=%s,Remote_Server_Port=%s,Local_Ext_IP=%s,Local_Port=%s\n", $1,$2,$3,$4,$5,$6,$7,$8,$9}'`

Outpu:
`Established=1617750506,Status=CONNECTED,dontknow=SUCCESS,Assigned_IP=10.39.112.15,Remote_Server_IP=212.102.37.151,Remote_Server_Port=1198,Local_Ext_IP=76.109.105.222,Local_Port=61613`

What data are you pulling?
