### ISSUE TITLE
Plugin telegraf_pfifgw.php  - Error in plugin: metric parse error: expected tag at 10:6: "Array"

### ISSUE THREAD

**Issue by xppx99** [VictorRobellini/pfSense-Dashboard#39]
Hello! 

First of all, let me thank you for your great work. I've just found it and it's now my preferred way to monitor pfsense. 

I've encontered a problem with the Plugin "telegraf_pfifgw.php" that I dont know how to solve. I tried to repeat the instalation process 2 times, but then found the "debug" flag inside the php plugin code, and activated it. 

From then, and after activating the debug mode in telegraf, there I found an error:
2021-06-11T21:34:00Z E! [inputs.exec] Error in plugin: metric parse error: expected tag at 10:6: "Array"

I've attached the output I got when running the telegraf_pfifgw.php program manually: https://pastebin.com/raw/mvzGjg9r

Note: I replaced/hided my WAN_IP and VPN_MONITOR_IP for obvious reasons 
Thanks

Edit: forgot to mension: 
pfsense version: 2.5.1

**Comment by VictorRobellini** [comment]
I think I see it, but whatever is generating that output is not from my repo as far as I can tell.  From just a quick scan "tiername" is null in your above output.  The problem is that I can't find anything named "tiername" is the most recent php script.  Telegraf doesn't like nulls.  Where did you get telegraf_pfifgw.php?

It should be as simple as, but without the code I have no idea.


if (!isset($tiername)){
      $tiername= "Unavailable";
      }

**Comment by VictorRobellini** [comment]
I'll dig through the debug output.  Most of the time it's just a null value that I forgot to check for.

**Comment by VictorRobellini** [comment]
RW_VPN shows a null value for LOSS.  I probably should just add a check for any null value.  

Give me a few to post an update

**Comment by VictorRobellini** [comment]
I tested it on my system and it works perfectly but I also don't have monitoring disabled on any of my interfaces.

https://github.com/VictorRobellini/pfSense-Dashboard/commit/a6fa2eca0572610d0f91c493eb752eaddd194e6c
