### ISSUE TITLE
More detailed traffic dashboards using ntopng?

### ISSUE THREAD

**Issue by jasonmbautista** [VictorRobellini/pfSense-Dashboard#46]
I've installed ntopng package to view a lot of the data on hosts, flows etc. I can see I can point ntopng to my influxdb instance that I've setup for this dashboard, it would seem like you could potentially provide even more dashboards using ntopng as a data source. Is that something that could be looked at for future builds?

**Comment by VictorRobellini** [comment]
I've absolutely looked into it.  I even setup softflow to collect stats into the telegraf sflow plugin to avoid using ntop.  The problem is that I don't have enough influx experience.  Sflow generates lots of data and unless you take the time to setup data rollups/downsampling and the right indexes, the DB be super slow until the disk fills, then it will crash.

Sorry, I had to scratch it off my list.
